#spring.application.name=Oauth2-server
server:
  port: 8079
spring:
  output.ansi.enabled: ALWAYS
  datasource:
    url: jdbc:postgresql://172.17.0.1:5432/oa2_server
    username: postgres
    password: mysecretpassword
  sql:
    init:
      mode: always